### ISSUE TITLE
[foonathan_memory] Progress Toward Quality Level 1 [13756]

### ISSUE THREAD

**Issue by brawner** [eProsima/foonathan_memory_vendor#23] opened 2020-03-31 00:34 UTC
This issue tracks the progression of the imported third-party package `foonathan_memory` to Quality Level 1 and a 1.0 version level. It follows the outline described in [REP 2004](https://github.com/ros-infrastructure/rep/blob/c2ba03bac23b8f313e47820833fad000dbbe058b/rep-2004.rst). 

* [ ] Version Policy
    - Appears to follow semver, but it's not declared explicitly
* [ ] Version >= 1.0.0
* [ ] Change Control Process
    - Many changes are committed directly without reviewers
* [-] PRs automatically tested
    - Ubuntu 16.04 for gcc 4.9 and 5.5, AMD 64
    - MacOS with XCode 9.4 with Apple LLVM version 9.1.0, AMD 64
    - Windows with Microsoft Visual Studio 2015, MSVC 18.0, AMD 64
    - Not tested on ARM 64

Documentation
* [x] Per-feature documentation. 
* [x] Per-item documentation in public API. 
* [x] Declared set of licenses
* [x] Copyright statement in each source file
* [x] Quality Declaration document
(https://github.com/eProsima/foonathan_memory_vendor/pull/22)

Testing:
* [x] System tests, which cover "features"
* [ ] Tests covering public API
    - Tests cover most public API
* [ ] Code coverage
    - Not tracked
* [ ] Performance tests
* [ ] Performance test policy
* [ ] Package code style
    - Not declared

Dependencies:
* [x] Third-party dependencies are Quality Level 1
    - c++ standard library

Platform Support
* [ ] Supports all tier 1 platforms
     - Untested explicitly on ARM 64 and current ROS Operating systems, but anecdotally tier 1 platforms are supported

**Comment by MiguelCompany** [comment] 2020-04-14 06:01
@brawner @Blast545 This seems like a duplicate of #21. Please check which one should be closed.

**Comment by brawner** [comment] 2020-04-14 06:34
Sort of... #21 is a description of `foonathan_memory_vendor`, while this issue strives to be about the third party package `foonathan_memory` itself. I didn't have any better place to put the issue for `foonathan_memory` other than here.

It's pretty clear that foonathan_memory is in maintenance mode only, so it seems unlikely that it will resolve its current issues to become the equivalent of QL 1. Do you all have any suggestions of how packages that depend on `foonathan_memory` might be able to declare themselves QL 1?

**Comment by brawner** [comment] 2020-05-28 23:31
Updated to reflect the added QD

**Comment by foonathan** [comment] 2020-12-02 12:06
I've just noticed this!

if there is anything you need, I'm completely willing to work with you.

**Comment by JLBuenoLopez** [comment] 2022-02-01 15:27
@brawner 

Fast DDS includes a [Quality Declaration](https://github.com/eProsima/Fast-DDS/blob/master/Quality_Declaration_foonathan_memory.md) of `foonathan memory` referring as well to the vendor package. I think this ticket can be closed.

**Closed as completed** 2023-03-28 06:49 UTC
